# Generated by Django 6.0 on 2026-01-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
        migrations.AddField(
            model_name='otp',
            name='identifier',
            field=models.CharField(default=12223, max_length=100),
            preserve_default=False,
        ),
    ]
