# Generated by Django 6.0 on 2026-02-06 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_user_address_owner_alter_address_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
