# Generated by Django 6.0 on 2026-02-08 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
