import type { Metadata } from "next";
import "./globals.css";
import RQProvider from "@/context/RQProvider";
import ContainerContextProvider from "@/context/container";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ContainerContextProvider>
          <RQProvider>{children}</RQProvider>
        </ContainerContextProvider>
      </body>
    </html>
  );
}
